default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: poketrade
  password: 'password'
  host: db

development:
  <<: *default
  database: poketrade_development

test:
  <<: *default
  database: poketrade_test

production:
  <<: *default
  database: poketrade_production
  username: poketrade
  password: <%= ENV['POKETRADE_DATABASE_PASSWORD'] %>
